### ISSUE TITLE
Accept to enable Versel app.

### ISSUE THREAD

**Issue by garronej** [codegouvfr/dsfr-react#3]
@bzg Salut :)
Vu que je te vois réveiller, si tu vois ça, est-ce que tu pourrais regarder tes mails, tu dois avoir une demande d'autorisation de versel d'accéder à l'organisation codegouvfr.  

Je ne suis pas owner donc je ne peux pas le faire moi-même.  

C'est pour mettre en ligne l'app de démo Next.js.  
Je ne peux pas utiliser page parce que ce n'est pas un site statique.  

À plus tard :)

**Comment by garronej** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/6702424/192165475-b2957481-2253-4dc8-bcbb-d6fb73d10b8d.png">

**Comment by bzg** [comment]
Merci pour le ping! J'avais vu la demande et je vais la valider mais c'est comme pour gitbook.com: il faut un chemin de sortie pour pouvoir publier sur nos serveurs et ne pas dépendre d'un service tiers.

**Comment by garronej** [comment]
Oui totalement!
Je ne compte rien publié avec vercel. 
C'est juste pour pouvoir avoir l'app de test en ligne et pouvoir montrer ou j'en suis a l'équipe DSFR sans qu'ils ai besoin de build.  
A titre perso Vercel j'evite pour ma prod.  
Trop captif comme platforme de deployment.
